<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Python Ruff</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.python</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.python.django</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.python.django.extended</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.python.ruff</string>
	<key>uuid</key>
	<string>D19B7248-BFB1-40A0-95D5-036E3425147D</string>
</dict>
</plist>
