module Constants
  TM_PYRUFF_DISABLE = !!ENV["TM_PYRUFF_DISABLE"]
  TM_PYRUFF = ENV["TM_PYRUFF"] || `command -v ruff`.chomp
  TM_PYRUFF_ENABLE_AUTOFIX = !ENV["TM_PYRUFF_ENABLE_AUTOFIX"].nil?
  TM_PYRUFF_OPTIONS = ENV["TM_PYRUFF_OPTIONS"]
  
  TM_PROJECT_DIRECTORY = ENV["TM_PROJECT_DIRECTORY"]
  TM_FILENAME = ENV["TM_FILENAME"]
  TM_FILEPATH = ENV["TM_FILEPATH"]

  TM_DOCUMENT_UUID = ENV["TM_DOCUMENT_UUID"]

  TOOLTIP_LINE_LENGTH = ENV["TM_PYRUFF_TOOLTIP_LINE_LENGTH"] || "100"
  TOOLTIP_LEFT_PADDING = ENV["TM_PYRUFF_TOOLTIP_LEFT_PADDING"] || "2"
  TOOLTIP_BORDER_CHAR = ENV["TM_PYRUFF_TOOLTIP_BORDER_CHAR"] || "-"
end